# Generated by Django 3.1.2 on 2020-10-17 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_auto_20201016_1928"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2020, 10, 17, 9, 43, 39, 321900),
                editable=False,
            ),
        ),
    ]
