# Generated by Django 3.1.2 on 2020-10-16 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 16, 15, 39, 37, 562685), editable=False),
        ),
    ]
